name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y libdbus-1-dev
    - name: Build
      run: cd code && cargo build --verbose
    - name: Run tests
      run: cd code && cargo test --verbose
